D20-1420: Add Voters to API
bfi-digital/polls-api-service pull request #5
Opened 2022-11-18 09:28 UTC by Dlair

This PR achieves the following:
- Renames `ingest` command to `ingest-results`
- Add new `ingest-voters` command to import voters data based on exported csv from Sight & Sound

2022-11-18 09:45 UTC, Dlair commented on app/Console/Commands/IngestVoters.php
> +// function find_index($array, $value, $default) {
I need to remove this as it's already defined elsewhere.

2022-11-21 11:03 UTC, PaulKiddle requested changes

2022-11-21 11:03 UTC, PaulKiddle commented on database/migrations/2022_11_15_120437_create_voters_table.php
> +            $table->string('surname');
If we're sorting by surname there should be an index on this column

2022-11-21 12:47 UTC, Dlair commented on database/migrations/2022_11_15_120437_create_voters_table.php
> +            $table->string('surname');
Thanks Paul, good spot! I added an index on `surname` since that's the default sort order.

2022-11-21 12:49 UTC, Dlair commented on app/Console/Commands/IngestVoters.php
> +// function find_index($array, $value, $default) {
Done

2022-11-21 14:35 UTC, PaulKiddle approved these changes

2022-11-21 14:48 UTC, merged